name: jd_py

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0-23/4, * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_py
jobs:
  build:
    
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x      
      - name: '运行同步'
        run: |
          git clone https://github.com/ClassmateLin/jd_scripts.git py
          cp -r py/*.py /home/runner/work/jd_py/jd_py
          cp -r py/utils/*.* /home/runner/work/jd_py/jd_py/utils
          rm -rf py
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "update by Action" -a || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.USER_TOKEN }}
          branch: ${{ github.ref }}
